name: WireMock Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    name: WireMock Sync
    steps:
      - uses: actions/checkout@v4
        with:
          repository: wiremock/wiremock
          token: ${{ secrets.WIREMOCK_SYNC_PAT }}
          ref: master
          fetch-depth: 0
      - id: checkout
        name: Check upstream
        run: |
          #!/bin/bash
          # Check latest semver tag:
          echo "Searching for latest semver"
          git tag -l --sort=-version:refname | grep -m 1
          # version=$(git tag -l --sort=-version:refname | grep -E '^\d+\.\d+\.\d+$' -m 1)
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "Found version=$version. Checking if this version is newer than our."

          gh release list
