name: WireMock Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    name: WireMock Sync
    steps:
      - uses: actions/checkout@v4
        with:
          #repository: wiremock/wiremock
          #token: ${{ secrets.WIREMOCK_SYNC_PAT }}
          #ref: master
          fetch-depth: 0
      - id: wiremock-remote
        name: Add WireMock remote
        run: |
          #!/bin/bash
          git remote add upstream https://github.com/wiremock/wiremock.git
          git fetch upstream

      - id: version-check
        name: Check Versions
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          #!/bin/bash
          # Check latest semver tag:
          echo "Searching for latest semver"
          wiremockVersion=$(git tag -l --sort=-version:refname | grep -P '^\d+\.\d+\.\d+$' -m 1)
          echo "wiremockVersion=${wiremockVersion}" >> $GITHUB_OUTPUT
          echo "Found wiremockVersion=${wiremockVersion}"

          guiVersion=$(gh release list --exclude-drafts --exclude-pre-releases --repo holomekc/wiremock | grep "Latest" | awk '{print $1}')
          echo "guiVersion=${guiVersion}" >> $GITHUB_OUTPUT
          echo "Found guiVersion=${guiVersion}"

          echo "Checking if WireMock version != WireMock-Gui version."
          echo "${wiremockVersion} != ${guiVersion}"

          [[ $guiVersion = ${wiremockVersion}* ]] && newVersion=0 || newVersion=1
          echo "newVersion=${newVersion}" >> $GITHUB_OUTPUT

          if [[ $newVersion == 0 ]]
          echo "No new version found. Nothing to do."
          then
          echo "A new version ${wiremockVersion} found."
          fi

      - id: create-pr
        if: ${{ steps.version-check.outputs.newVersion == 1 }}
        name: Create PR
        run: |
          #!/bin/bash
          # We cannot merge the upstream branch into our master branch and create a new branch.
          # There will always be a conflict and we need to adjust the version manually.
          git checkout -B sync/${{ steps.version-check.outputs.wiremockVersion }} ${{ steps.version-check.outputs.wiremockVersion }}

          # Merge master of wiremock-gui
          #gh pr create
